-- Migration: Import all existing questions into Supabase questions table
-- Generated automatically from question-bank.html, module1-newborn.html,
-- module2-maternal.html, diagnostic.html

INSERT INTO questions (stem, option_a, option_b, option_c, option_d, correct_answer, rationale, module_key, nclex_category, nclex_sub, topic, difficulty, is_ngn, active) VALUES
(
  'A newborn receives an APGAR score of 5 at 1 minute of life. How should the nurse interpret this finding and plan care?',
  'Normal (7–10) — document and continue routine newborn care',
  'Moderate difficulty (4–6) — stimulate the newborn and provide supplemental oxygen, reassess at 5 minutes',
  'Severe distress (0–3) — begin immediate resuscitation',
  'This score predicts the newborn''s long-term neurological outcomes and intelligence',
  'b',
  'APGAR 4–6 = moderate difficulty. Intervention includes stimulation, supplemental oxygen, and reassessment at 5 minutes. The APGAR is a snapshot of transition — it does NOT predict future intelligence or health.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is assessing a newborn 4 hours after birth. Which finding should be reported to the provider immediately?',
  'Acrocyanosis of the hands and feet',
  'Vernix caseosa covering the skin',
  'Central cyanosis of the lips and tongue',
  'Mongolian spots on the lower back',
  'c',
  'Central cyanosis (blue lips/tongue) is always an emergency — it indicates inadequate oxygenation and must be reported immediately.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is reviewing fetal circulation structures that close after birth. Which structure allows blood to bypass the fetal liver, shunting it directly from the umbilical vein to the inferior vena cava?',
  'Ductus arteriosus',
  'Foramen ovale',
  'Ductus venosus',
  'Umbilical artery',
  'c',
  'The ductus venosus connects the umbilical vein to the inferior vena cava, bypassing the liver. Memory trick: A V A — Arteries = Away (from baby) = 2, Vein = Visits (baby) = 1.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A parent asks the nurse why their newborn is receiving vitamin K immediately after birth. What is the nurse''s best response?',
  'It prevents eye infections that the baby may have been exposed to during delivery.',
  'Newborns are born with very low clotting factors. Vitamin K prevents hemorrhagic disease of the newborn.',
  'It is required by law in all states — it is a standard procedure with no specific reason for your baby.',
  'It prevents jaundice by helping the liver process bilirubin more efficiently.',
  'b',
  'Newborns lack sufficient vitamin K–dependent clotting factors at birth. Vitamin K prevents hemorrhagic disease of the newborn (HDN), which can cause serious or fatal bleeding.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A breastfeeding mother is concerned that her milk has not fully come in yet on day 2 postpartum. She asks how she will know if her newborn is getting enough. Which response by the nurse is most accurate?',
  'By day 2, your baby should have 6–8 wet diapers per day.',
  'By day 2, your baby should have at least 2 wet diapers — wet diapers are one of the best signs that feeding is adequate.',
  'Weight gain is the only reliable way to know — schedule a weight check tomorrow.',
  'Your baby should be sleeping at least 4 hours between feeds if getting enough milk.',
  'b',
  'Wet diaper count by day: Day 1→1, Day 2→2, Day 3→3, Day 4+→6–8. Wet diapers are one of the best indicators of adequate intake. By day 2, at least 2 wet diapers is expected.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is educating a nursing student about the dangers of cold stress in newborns. Which physiological consequence of cold stress is most important to understand?',
  'Cold stress causes decreased oxygen consumption and slows metabolic rate',
  'Cold stress increases surfactant production and stabilizes respiratory function',
  'Cold stress increases blood glucose levels as the body burns fat for heat',
  'Cold stress increases oxygen consumption and metabolic demand, which can cause hypoglycemia and respiratory distress',
  'd',
  'Cold stress triggers nonshivering thermogenesis (brown fat metabolism), which increases oxygen consumption and metabolic demand — leading to hypoglycemia, decreased surfactant effectiveness, and respiratory distress. Cold babies become hypoglycemic babies.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse assesses a 1-hour-old newborn and documents the following: grunting on expiration, nasal flaring, and visible intercostal retractions. How should the nurse interpret these findings?',
  'These are normal transitional breathing patterns expected in the first hour of life',
  'These are signs of respiratory distress requiring immediate nursing intervention',
  'These findings are expected in a newborn who has been crying vigorously',
  'These indicate the newborn is hungry and needs to be fed immediately',
  'b',
  'Grunting, nasal flaring, and chest retractions are the classic warning signs of neonatal respiratory distress. The ABCs come first — Airway, Breathing, Circulation — and this newborn needs immediate assessment and intervention.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse strokes the outer edge of a newborn''s foot from heel to toe and observes dorsiflexion of the big toe with fanning of the remaining toes. Which reflex has the nurse elicited?',
  'Moro reflex',
  'Palmar grasp reflex',
  'Babinski reflex',
  'Tonic neck (fencer) reflex',
  'c',
  'The Babinski reflex is elicited by stroking the outer sole of the foot — resulting in dorsiflexion of the big toe and fanning of the others. This is a normal newborn finding (abnormal in adults).',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A new mother is tearful and tells the nurse, ''My baby has lost weight since birth — I must not be producing enough milk.'' How should the nurse respond?',
  'You''re right to be concerned — weight loss in a newborn is abnormal and I''ll notify the provider.',
  'Weight loss of up to 10% in the first few days is normal. Birth weight is typically regained by 10–14 days. Wet diapers and feeding cues are the best daily guides.',
  'Any weight loss means we need to start formula supplementation right away.',
  'Newborns should not lose any weight in the first 24 hours — this needs to be evaluated.',
  'b',
  'Weight loss up to 10% of birth weight in the first few days is physiologically normal as the newborn transitions from amniotic fluid and passes meconium. Birth weight should be regained by 10–14 days. Wet diaper count is the most practical daily indicator of adequacy.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse assesses a newborn and notes yellowing of the skin at 36 hours of age. The newborn is feeding well and appears otherwise healthy. How should the nurse classify this jaundice?',
  'Pathological — report immediately; jaundice should not appear until after 48 hours',
  'Physiological — this is an expected, normal finding; jaundice appearing after 24 hours is physiologic',
  'Concerning — this timing suggests ABO blood type incompatibility',
  'Normal — jaundice within the first 24 hours is always expected and reassuring',
  'b',
  'Physiologic jaundice appears AFTER 24 hours (typically day 2–3), peaks on days 3–5, and resolves within 1–2 weeks. At 36 hours in a well-feeding newborn, this is physiologic. KEY PEARL: Jaundice in the FIRST 24 hours is ALWAYS pathological and must be reported.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse assesses a newborn at 1 minute of life: heart rate 90 bpm, weak cry, some flexion of extremities, grimace only when stimulated, body pink with blue hands and feet. What is the APGAR score and the nurse''s priority action?',
  'Score 5 — provide stimulation and supplemental oxygen; reassess at 5 minutes',
  'Score 7 — document findings and continue routine newborn care',
  'Score 3 — initiate immediate resuscitation',
  'Score 8 — reassure the parents; reassess at 5 minutes with no intervention needed',
  'a',
  'HR 90 (score 1) + weak cry (1) + some flexion (1) + grimace (1) + acrocyanosis (1) = APGAR 5. Score 4–6 = moderate difficulty → stimulate and provide supplemental O₂, reassess at 5 minutes.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is assessing a 12-hour-old newborn during routine nursery rounds. Select ALL findings that require immediate provider notification.',
  'Acrocyanosis of the hands and feet',
  'Persistent nasal grunting between feedings',
  'Central cyanosis of the lips and tongue',
  'Vernix caseosa on the skin folds',
  'b',
  'Persistent grunting (respiratory distress sign), central cyanosis (oxygenation emergency), and apnea (always reportable) are all findings requiring immediate provider notification.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  true,
  true
),
(
  'A nurse assesses a 2-hour-old term newborn: respiratory rate 74 breaths/min, central cyanosis, intercostal retractions, and audible grunting. SpO₂ is 86% on room air. What is the nurse''s priority action?',
  'Document the findings thoroughly and reassess in 30 minutes',
  'Ensure the airway is open, call for immediate assistance, and prepare supplemental oxygen',
  'Warm the newborn under the radiant warmer to rule out cold stress first',
  'Feed the newborn to provide glucose and stimulate respiratory effort',
  'b',
  'ABCs come first — Airway, Breathing, Circulation. Central cyanosis with SpO₂ 86%, retractions, and grunting represent a respiratory emergency. The nurse must ensure the airway is patent and call for immediate help while preparing oxygen.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A 4-hour-old newborn is jittery, has a weak cry, and is difficult to arouse. Point-of-care blood glucose is 36 mg/dL. What is the nurse''s first action?',
  'Draw a full metabolic panel and wait for results before intervening',
  'Feed the newborn (breast or formula) if feeding is appropriate, and follow facility hypoglycemia protocol',
  'Immediately administer IV dextrose without attempting oral feeding first',
  'Place the newborn under a radiant warmer and recheck glucose in 2 hours',
  'b',
  'The first intervention for neonatal hypoglycemia is feeding if the newborn can tolerate oral intake — per infographic Concept #13 and standard facility protocols. After feeding, glucose is rechecked in 30 minutes to assess response.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is planning immediate care for a newborn following vaginal delivery. Select ALL interventions that prevent heat loss and support thermoregulation.',
  'Dry the newborn immediately with warm blankets',
  'Place the newborn on a cold infant scale for immediate birth weight',
  'Maintain a warm, draft-free environment in the delivery room',
  'Encourage skin-to-skin contact with the parent',
  'a',
  'Drying (prevents evaporative loss), warm environment (prevents convective loss), skin-to-skin (provides warmth and regulates temp), hat (head loses significant heat), and swaddling (insulation) are all thermoregulation interventions from Concept #11.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  true,
  true
),
(
  'A nurse is providing discharge teaching to parents about safe sleep practices. Which statement by a parent indicates a need for further teaching?',
  'I will always place my baby on her back to sleep.',
  'We bought a firm, flat crib mattress with a fitted sheet.',
  'I''ll put a soft blanket in the crib at night so she stays warm.',
  'She can sleep in our room in her own bassinet for the first few months.',
  'c',
  'Soft blankets, pillows, bumpers, and stuffed animals in the sleep space are suffocation hazards. The safe sleep environment includes: back to sleep, firm mattress, no soft objects, room sharing (not bed sharing). Safe sleep prevents SIDS.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is providing discharge teaching to parents about umbilical cord care. Which instruction should the nurse include?',
  'Apply antibiotic ointment to the cord stump daily to prevent infection.',
  'Fold the diaper below the stump, keep it clean and dry, and expect it to fall off in 7–14 days.',
  'Submerge the newborn in a tub bath daily — this will help soften and remove the cord faster.',
  'The cord should fall off within 3–4 days. Call the provider immediately if it lasts longer.',
  'b',
  'Umbilical cord care: keep it clean and dry, fold the diaper below the stump to allow air exposure, and expect the stump to fall off in 7–14 days. Report redness, drainage, foul odor, or swelling.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A home health nurse visits a 5-day-old breastfed newborn. The mother reports the newborn had 4 wet diapers yesterday. How should the nurse interpret this?',
  'Normal — 4 wet diapers is age-appropriate for a 5-day-old',
  'Concerning — starting on day 4, newborns should have 6–8 wet diapers per day; 4 diapers suggests inadequate intake',
  'Normal — wet diaper count peaks on day 3 and naturally decreases after that',
  'Concerning — a 5-day-old should have at least 10 wet diapers per day',
  'b',
  'Wet diaper milestone: Day 4+ → 6–8 wet diapers per day. At day 5, only 4 wet diapers suggests the newborn is not getting adequate milk — this warrants assessment of latch, feeding frequency, and a weight check.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for newborns in the nursery. Select ALL findings that require immediate notification of the provider.',
  'Mongolian spots on the sacral area',
  'Central cyanosis of the lips and tongue',
  'Apnea episode observed during assessment',
  'Acrocyanosis of the hands and feet',
  'b',
  'Central cyanosis, apnea, seizures, temperature instability, and lethargy/poor feeding are all findings from Concept #17 (Report Immediately) that require urgent provider notification.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  true,
  true
),
(
  'A nursing student observes a newborn with blue discoloration of the hands and feet and asks the nurse, ''Should I report this? Is this a problem?'' What is the nurse''s best teaching response?',
  'Yes — any blue discoloration in a newborn is a cardiac emergency and must be reported immediately.',
  'No — blue hands and feet (acrocyanosis) is a normal finding as peripheral circulation adjusts. Blue lips and tongue is the emergency we watch for.',
  'Yes — this is central cyanosis and we need to prepare oxygen immediately.',
  'No — newborns appear blue all over for the first 24 hours, so no assessment is needed.',
  'b',
  'This is one of the most common NCLEX traps on newborn care. Acrocyanosis (blue extremities) = NORMAL. Central cyanosis (blue lips/tongue/trunk) = EMERGENCY. The NCLEX tests whether you know the difference.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  false,
  true
),
(
  'Which single finding in this assessment is the most immediately life-threatening and requires priority action?',
  'Heart rate of 182 bpm',
  'Central cyanosis of the lips with SpO₂ of 86%',
  'Respiratory rate of 78 breaths/min',
  'Temperature of 37.0°C',
  'b',
  'Central cyanosis (blue lips) with SpO₂ of 86% indicates severe hypoxemia. This is the most immediately life-threatening finding — it reflects inadequate oxygenation and requires urgent airway and oxygen intervention. ABCs come first.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  true,
  true
),
(
  'How should the nurse classify the jaundice in this newborn?',
  'Physiological — jaundice appearing after 12 hours is a normal expected finding',
  'Pathological — jaundice appearing within the first 24 hours of life is always concerning',
  'Normal — all newborns develop visible jaundice in the first 24 hours',
  'Mild — monitor at home and reassess at the 2-week well visit',
  'b',
  'CRITICAL PEARL: Jaundice within the FIRST 24 hours is ALWAYS pathological. Physiologic jaundice appears AFTER 24 hours. This newborn has jaundice at 18 hours — this is pathological and requires immediate investigation.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  true,
  true
),
(
  'A nurse is making rounds in the newborn nursery and assessing several infants. Select ALL findings that require IMMEDIATE intervention — prioritized above documentation, family communication, or routine care.',
  'Central cyanosis of the lips in a 3-hour-old newborn',
  'Grunting and nasal flaring with respiratory rate of 78 in a 1-hour-old',
  'Mongolian spots noted on the sacral area of a 2-day-old',
  'Blood glucose 36 mg/dL with jitteriness in a 2-hour-old LGA infant',
  'a',
  'Central cyanosis (oxygenation emergency), respiratory distress signs (RDS), symptomatic hypoglycemia, hypothermia with lethargy (cold stress), and apnea (always report immediately) all require priority intervention.',
  'm1',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  true,
  true
),
(
  'A nurse is educating a group of prenatal patients about blood type incompatibility. Which scenario places a fetus at risk for hemolytic disease of the newborn?',
  'Rh-positive mother carrying an Rh-positive fetus',
  'Rh-negative mother carrying an Rh-positive fetus',
  'Rh-positive mother carrying an Rh-negative fetus',
  'Rh-negative mother carrying an Rh-negative fetus',
  'b',
  'When an Rh-negative mother carries an Rh-positive fetus, fetal Rh-positive RBCs can cross the placenta, causing the mother to develop anti-Rh antibodies. In subsequent pregnancies, these antibodies attack the fetus''s RBCs — causing hemolytic disease of the newborn. KEY PEARL: Rh– mom + Rh+ baby = risk. RhoGAM prevents sensitization.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'An Rh-negative patient delivers an Rh-positive infant. The nurse knows that RhoGAM (Rho(D) immune globulin) must be administered within which timeframe postpartum?',
  'Within 24 hours of delivery',
  'Within 48 hours of delivery',
  'Within 72 hours of delivery',
  'Within 7 days of delivery',
  'c',
  'RhoGAM must be administered within 72 hours (3 days) postpartum to prevent the Rh-negative mother from becoming sensitized to Rh-positive blood. It is also given routinely at 28 weeks gestation, and after any sensitizing event (miscarriage, amniocentesis, trauma, ectopic pregnancy, etc.).',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is reviewing the diagnostic criteria for preeclampsia with a student nurse. Which combination of findings establishes a diagnosis of preeclampsia?',
  'Blood pressure ≥130/80 mmHg on one occasion after 16 weeks gestation',
  'Blood pressure ≥140/90 mmHg on two occasions 4 hours apart, with proteinuria ≥300 mg/24 hours, after 20 weeks gestation',
  'Any elevated blood pressure before 20 weeks gestation with headache and edema',
  'Blood pressure ≥160/110 mmHg on one occasion with severe headache and visual changes',
  'b',
  'Preeclampsia is diagnosed by BP ≥140/90 mmHg (measured on two occasions, at least 4 hours apart) WITH proteinuria ≥300 mg/24 hours (or 3+ on dipstick), occurring after 20 weeks gestation. NCLEX CLUE: Must be AFTER 20 weeks — before 20 weeks with hypertension suggests chronic hypertension, not preeclampsia.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is reviewing a patient''s labs and sees: low platelets, elevated liver enzymes, and indirect signs of hemolysis. The nurse recognizes these findings as consistent with which obstetric complication?',
  'Gestational diabetes with hepatic involvement',
  'HELLP syndrome — a severe variant of preeclampsia',
  'Normal third-trimester lab changes related to increased blood volume',
  'Preterm labor with associated inflammatory response',
  'b',
  'HELLP syndrome = Hemolysis + Elevated Liver enzymes + Low Platelets. It is a severe, life-threatening variant of preeclampsia. MEMORY TRICK: H-E-L-L-P spells out the findings. These lab abnormalities combined in a pregnant patient require immediate provider notification — HELLP can rapidly progress to maternal and fetal death.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse observes early decelerations on the fetal monitor — the FHR dips symmetrically and returns to baseline with each contraction. What is the most appropriate nursing interpretation?',
  'This is a late deceleration pattern — notify the provider immediately and prepare for emergency delivery',
  'This pattern indicates cord compression — reposition the patient to the left lateral position',
  'Early decelerations reflect head compression during contractions and are a normal, benign finding',
  'This is minimal variability — a sign of possible fetal distress requiring immediate intervention',
  'c',
  'Early decelerations are caused by vagal response to fetal HEAD COMPRESSION during contractions. They are BENIGN, symmetric, mirror contractions exactly, and require NO intervention. KEY PEARL: Early = head compression = benign = no action needed. Compare: Late = placental insufficiency = dangerous = act immediately.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is monitoring a laboring patient and notices recurrent decelerations that begin AFTER the peak of each contraction and return to baseline slowly. Which action is the nurse''s PRIORITY?',
  'Document the finding and continue routine monitoring — this is expected during active labor',
  'Reposition the patient, apply oxygen, increase IV fluids, and notify the provider immediately',
  'Encourage the patient to push with the next contraction to expedite delivery',
  'Administer oxytocin to strengthen contractions and improve placental blood flow',
  'b',
  'Late decelerations = placental insufficiency. They begin AFTER the contraction peak, indicate the fetus is not getting adequate oxygen through the placenta, and are NEVER normal. Nursing priorities: Reposition (left lateral), O₂ via face mask, IV fluids, stop oxytocin if running, and NOTIFY the provider. NCLEX PEARL: Late decelerations = dangerous = act immediately.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is performing fundal height assessments on three patients. Which finding correctly corresponds to gestational age based on standard fundal height landmarks?',
  'At 12 weeks, fundal height is palpable at the umbilicus',
  'At 20 weeks, fundal height is approximately at the umbilicus; at 36 weeks, it reaches the xiphoid process',
  'At 28 weeks, the fundal height is at the umbilicus and does not change until term',
  'Fundal height rises above the xiphoid process by 32 weeks, then remains at the same level',
  'b',
  'Standard fundal height landmarks: 12 weeks = just above pubic symphysis; 20 weeks = at the umbilicus (and fundal height in cm ≈ gestational age in weeks); 36 weeks = at the xiphoid process. Lightening (fetal descent into the pelvis) drops the fundus before labor. NCLEX CLUE: 20 weeks at umbilicus is the most-tested landmark.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is reviewing vaccine safety with a group of pregnant patients. Select ALL vaccines that are considered safe and recommended during pregnancy.',
  'Tdap (27–36 weeks)',
  'Influenza — injectable (inactivated)',
  'MMR (measles, mumps, rubella)',
  'COVID-19 vaccine',
  'a',
  'Safe/recommended in pregnancy: Tdap (27–36 weeks to protect newborn against pertussis), Influenza injectable/inactivated (live FluMist is NOT safe), COVID-19, and RSV (32–36 weeks seasonally). Hepatitis B is also safe if indicated.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  true,
  true
),
(
  'A nurse is teaching a patient at 30 weeks gestation how to perform daily kick counts. Which instruction is most accurate?',
  'Count fetal movements after each meal; report to the provider if you feel fewer than 5 movements per hour',
  'After 28 weeks, count fetal movements daily. The fetus should move at least 10 times in 2 hours. Call the provider if fewer movements are felt.',
  'Fetal movement is most active in the morning — always count before breakfast for best accuracy',
  'Kick counts are only necessary in the third trimester if there are risk factors like gestational diabetes or preeclampsia',
  'b',
  'Kick count guidelines: Begin after 28 weeks; count daily; the fetus should produce at least 10 movements in 2 hours. If fewer than 10 movements in 2 hours, call the provider. Decreased fetal movement can be an early sign of fetal distress and requires immediate evaluation.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A student nurse asks about which lab finding is considered NORMAL during pregnancy. Which response by the charge nurse is most accurate?',
  'Proteinuria of 1+ on dipstick is a normal finding in any trimester — document and monitor',
  'WBC of 12,000/mm³ is highly abnormal in pregnancy and suggests active infection requiring immediate evaluation',
  'Mild dilutional anemia and WBC up to 16,000/mm³ are normal adaptations; trace glucosuria may occur without indicating diabetes',
  'Elevated uric acid and creatinine are expected changes from increased renal blood flow',
  'c',
  'Normal pregnancy labs: WBC 5,000–16,000/mm³ (mild leukocytosis is normal); Hgb/Hct ↓ (dilutional anemia due to plasma volume expansion); Platelets 150,000–400,000; Glucose — trace ↑ after meals is OK (↑GFR exceeds reabsorption threshold); BUN/Creatinine ↓ (increased GFR); Coagulation → hypercoagulable (↑fibrinogen). NCLEX TRAP: Proteinuria is NEVER normal in pregnancy — it is always a red flag.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is triaging two laboring patients. Patient A reports sudden, severe abdominal pain with a rigid, board-like uterus and dark red vaginal bleeding. Patient B reports painless, bright red vaginal bleeding with no contractions. Which statement BEST distinguishes these two patients?',
  'Both patients have placenta previa — the color difference is not clinically significant',
  'Patient A has signs of placental abruption (painful, dark bleeding, rigid uterus); Patient B has signs of placenta previa (painless, bright red bleeding)',
  'Patient B''s bleeding is more dangerous because bright red blood indicates arterial hemorrhage',
  'Patient A''s rigid uterus indicates normal early labor — it does not require immediate intervention',
  'b',
  'NCLEX PEARL to memorize: Abruption = Painful dark bleeding + rigid uterus (premature separation of placenta). Previa = Painless bright red bleeding (placenta over cervical os, disrupted by cervical changes). Both are emergencies — notify provider immediately for both. But the presentations are completely different and the NCLEX will test this distinction.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A patient at 32 weeks gestation presents with sudden onset painless bright red vaginal bleeding. The nurse suspects placenta previa. Which nursing action is the PRIORITY?',
  'Perform a vaginal examination to assess cervical dilation and determine if labor has begun',
  'Administer oxytocin to prepare the cervix and facilitate safe delivery',
  'Do NOT perform a vaginal examination — notify the provider immediately and monitor maternal and fetal status',
  'Prepare the patient for amniotomy to reduce intrauterine pressure and slow the bleeding',
  'c',
  'NEVER perform a vaginal examination with suspected or confirmed placenta previa — the examining finger can rupture the placental tissue over the cervical os, causing massive, life-threatening hemorrhage. Nursing priorities: NO vaginal exam, notify provider, continuous fetal monitoring, IV access, type and screen/crossmatch, keep NPO. NCLEX TRAP: This is the #1 tested contraindication for placenta previa.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse assesses a patient whose membranes just ruptured and finds the umbilical cord visible at the vaginal introitus. Which nursing action is the PRIORITY?',
  'Push the cord gently back into the uterus and prepare the patient for continued labor monitoring',
  'Place the patient in knee-chest or Trendelenburg position and use two gloved fingers to lift the presenting part off the cord — do NOT push the cord back — call for help immediately',
  'Administer oxytocin to strengthen contractions and accelerate delivery before cord compression occurs',
  'Encourage the patient to push with the next contraction to facilitate rapid vaginal delivery',
  'b',
  'Cord prolapse = obstetric emergency. Priority: (1) Call for emergency help, (2) Knee-chest or Trendelenburg position to use gravity to shift the fetus off the cord, (3) Two gloved fingers inside vagina to manually lift/hold the presenting part OFF the cord — maintain this until delivery. DO NOT push the cord back (causes vasospasm). Emergency cesarean is usually required. NCLEX PEARL: Preserve cord circulation until delivery — every second matters.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse notices variable decelerations on the fetal monitor — abrupt drops in FHR that vary in timing and depth relative to contractions. What is the priority nursing action?',
  'Notify the provider immediately for emergency cesarean delivery',
  'Increase the oxytocin infusion rate to improve uteroplacental blood flow',
  'Reposition the patient (left lateral or hands-and-knees), apply oxygen, and increase IV fluids; notify the provider if pattern persists',
  'Variable decelerations are always benign — document and continue routine monitoring',
  'c',
  'Variable decelerations = cord compression. They are characterized by abrupt drops, V-shape or U-shape pattern, varying in timing relative to contractions. Initial nursing actions: REPOSITION (left lateral, hands-and-knees, or Trendelenburg to relieve cord pressure), apply O₂ at 8–10 L/min via face mask, increase IV fluids. Notify provider if variables are severe (drop >60 bpm, lasting >60 seconds) or persist. NCLEX CLUE: Variable = cord compression.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A patient with severe preeclampsia is receiving IV magnesium sulfate for seizure prophylaxis. The nurse assesses respirations of 10 breaths/min, absent deep tendon reflexes, and decreased urine output. Which action is the nurse''s PRIORITY?',
  'Increase the magnesium infusion rate — the patient''s seizure risk is still elevated',
  'Stop the magnesium infusion immediately and administer calcium gluconate — these findings indicate magnesium toxicity',
  'Administer a bolus of IV fluid to increase urine output and dilute the magnesium level',
  'These are expected side effects of magnesium — document and continue the infusion at the current rate',
  'b',
  'Magnesium TOXICITY signs: respiratory rate <12 breaths/min, absent deep tendon reflexes (especially patellar reflex), decreased urine output (<30 mL/hr), and decreased LOC. ANTIDOTE: Calcium gluconate IV. Stop the infusion immediately. Keep calcium gluconate at the bedside for ALL patients on magnesium sulfate. NCLEX PEARL: Mag toxicity → STOP mag → GIVE calcium gluconate.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A patient''s chart records her obstetric history as G4 T2 P1 A1 L2. How should the nurse correctly interpret this GTPAL notation?',
  '4 total pregnancies; 2 term births; 1 preterm birth; 1 abortion/loss; 2 living children',
  '4 term births; 2 preterm births; 1 abortion; 1 living child',
  '4 total pregnancies; all at term; 2 living children; 1 miscarriage',
  'Gravida 4 means she is currently 4 months pregnant; 2 previous term deliveries',
  'a',
  'GTPAL: G = Gravida (total pregnancies, including current); T = Term births (≥37 weeks); P = Preterm births (20–36+6 weeks); A = Abortions/losses (spontaneous or induced, <20 weeks); L = Living children. So G4 T2 P1 A1 L2 = 4 pregnancies total; 2 term births; 1 preterm birth; 1 abortion; 2 living children. NCLEX TIP: L (living children) can be LESS than T+P if a child died.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'An Rh-negative patient at 14 weeks gestation has a positive indirect Coombs test. What is the most important nursing implication?',
  'Administer RhoGAM immediately — positive Coombs means she needs it now',
  'Do NOT administer RhoGAM — a positive indirect Coombs indicates she is already sensitized; RhoGAM will not prevent further sensitization',
  'Repeat the test at 28 weeks gestation before making any clinical decisions',
  'Administer RhoGAM and schedule weekly fetal monitoring to detect antibody formation',
  'b',
  'NCLEX TRAP: Do NOT give RhoGAM if the mother is already sensitized (positive indirect Coombs = maternal anti-Rh antibodies already present). RhoGAM PREVENTS sensitization — it cannot reverse it once it has occurred. Instead, these patients require serial fetal surveillance (middle cerebral artery Doppler studies, possible intrauterine transfusion) to monitor for fetal hemolytic disease.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is working on a prenatal unit. Select ALL findings that require IMMEDIATE provider notification.',
  'Vaginal bleeding at any gestational age',
  'Mild bilateral ankle edema at 36 weeks',
  'Leaking fluid from the vagina before term',
  'Fever and chills in a pregnant patient',
  'a',
  'Report immediately: Vaginal bleeding (placenta previa, abruption, or other emergency); leaking fluid (premature rupture of membranes → infection/cord prolapse risk); fever/chills (chorioamnionitis or other infection); severe facial/hand swelling (preeclampsia sign); dizziness/syncope (possible hemodynamic compromise).',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  true,
  true
),
(
  'A nurse is reviewing urinalysis results for three pregnant patients. Which finding requires IMMEDIATE provider notification?',
  'Trace glucosuria with a normal blood glucose in a 28-week patient',
  'Trace proteinuria on a single dipstick reading in a 20-week patient with no other symptoms',
  '3+ proteinuria on dipstick in a patient with BP 148/96 and severe headache',
  'WBC 14,000/mm³ in a 32-week patient with no fever or symptoms',
  'c',
  '3+ proteinuria + BP 148/96 + severe headache = preeclampsia with concerning features — this requires IMMEDIATE provider notification. NCLEX TRAP: While trace proteinuria can be normal, SIGNIFICANT proteinuria (>300 mg/24hr, or 2+ or more on dipstick) combined with hypertension is the diagnostic hallmark of preeclampsia. Proteinuria is NEVER written off when accompanied by elevated BP and symptoms.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse receives four messages simultaneously. Which patient should the nurse assess FIRST?',
  'A 38-week patient reporting irregular Braxton Hicks contractions every 20 minutes',
  'A 30-week patient with 2+ ankle edema and mild lower back pain',
  'A 34-week patient with BP 170/110, severe headache, and upper abdominal pain',
  'A 24-week patient with round ligament pain and mild shortness of breath',
  'c',
  'BP 170/110 = SEVERE-RANGE hypertension in pregnancy (≥160/110 requires treatment within 30–60 minutes). Combined with severe headache and upper abdominal pain (RUQ/epigastric pain = hepatic involvement → possible HELLP), this patient has preeclampsia with severe features — a life-threatening emergency. ALWAYS use the ''MOM FIRST'' framework: most dangerous presentation first.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  false,
  true
),
(
  'Which assessment finding requires PRIORITY nursing action before initiating the magnesium sulfate infusion?',
  'Establish IV access and obtain baseline weight',
  'Assess and document baseline vital signs, DTRs, level of consciousness, urine output, and fetal heart rate — then initiate infusion per order',
  'Obtain a 24-hour urine collection before starting any medications',
  'Administer oral labetalol and reassess blood pressure before initiating magnesium',
  'b',
  'Before initiating magnesium sulfate, establish a complete BASELINE: vital signs, deep tendon reflexes (to detect toxicity progression), level of consciousness, urine output (≥30 mL/hr required — mag is renally cleared, so poor urine output = toxicity risk), and fetal heart rate. Without a documented baseline, toxicity assessment during the infusion has no comparison point.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  true,
  true
),
(
  'Using the ''MOM FIRST'' priority framework, in what order should the nurse assess these patients? Select the patient who should be seen FIRST.',
  'Patient C — 39-week patient with irregular contractions is closest to term and most likely to deliver',
  'Patient A — sudden severe pain, rigid uterus, and dark bleeding suggest placental abruption, which poses an immediate risk to both mother and fetus',
  'Patient D — regular contractions at 28 weeks indicate preterm labor and require urgent tocolysis',
  'Patient B — bright red bleeding is always the most emergent presentation',
  'b',
  'Patient A has classic placental abruption: sudden severe pain + rigid uterus + dark red bleeding = premature placental separation. Blood may be concealed behind the placenta — visible bleeding underestimates true hemorrhage. Maternal hemorrhagic shock and fetal death can occur rapidly. This is the highest-acuity patient: immediate assessment, large-bore IV access, type and crossmatch, continuous fetal monitoring, provider notification.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  true,
  true
),
(
  'A nurse is conducting rounds on the antepartum unit. Select ALL findings that require IMMEDIATE provider notification — prioritized above all other tasks.',
  'BP 172/114 with severe headache and RUQ pain in a 34-week patient',
  'Mild ankle edema with trace glucosuria in a 32-week patient',
  'Painless bright red vaginal bleeding at any gestational age',
  'WBC 12,000 and Hgb 10.5 in a 28-week patient on prenatal vitamins',
  'a',
  'BP 172/114 + headache + RUQ pain = severe preeclampsia/possible HELLP — life-threatening emergency; painless vaginal bleeding = possible placenta previa or other hemorrhagic emergency requiring immediate evaluation; no fetal movement for 5 hours after attempted kick counts = possible fetal compromise requiring immediate NST or BPP; urine output 20 mL/hr on magnesium = <30 mL/hr threshold indicates magnesium toxicity risk — infusion may need to be stopped.',
  'm2',
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  true,
  true
),
(
  'A registered nurse is preparing to delegate tasks at the start of the shift. Which task is most appropriate to delegate to an unlicensed assistive personnel (UAP)?',
  'Assessing bilateral breath sounds after bronchodilator therapy',
  'Ambulating a stable post-op day 2 client to the hallway',
  'Educating a diabetic client on insulin self-injection technique',
  'Interpreting a client''s telemetry rhythm change',
  'b',
  'Ambulating a stable post-op day 2 client is a routine task requiring no clinical judgment — appropriate for UAP.',
  NULL,
  'safe_effective_care',
  'Management of Care',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is using the SBAR communication tool to report a change in a client''s condition to the provider. Which component addresses the nurse''s clinical assessment of the problem?',
  'Situation',
  'Background',
  'Assessment',
  'Recommendation',
  'c',
  'Assessment is the nurse''s clinical interpretation of what is happening — the ''A'' in SBAR.',
  NULL,
  'safe_effective_care',
  'Management of Care',
  NULL,
  'medium',
  false,
  true
),
(
  'A charge nurse observes a new graduate RN performing a sterile dressing change using incorrect technique. What is the charge nurse''s priority action?',
  'Document the incident and address it at the next staff meeting',
  'Immediately intervene and assist the nurse to complete the dressing change correctly',
  'Complete an incident report and notify the manager',
  'Ask the client if they noticed the error',
  'b',
  'Client safety is the immediate priority — the charge nurse must intervene to correct the technique before harm occurs.',
  NULL,
  'safe_effective_care',
  'Management of Care',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for four clients. Which client should be assigned to the traveling (agency) nurse?',
  'A client with COPD admitted 2 days ago, stable on 2L O2 via nasal cannula',
  'A client admitted this morning with new-onset chest pain awaiting cardiac workup',
  'A client post-op day 1 following a coronary artery bypass graft',
  'A client with diabetic ketoacidosis receiving an insulin drip',
  'a',
  'The stable COPD client on 2L O2 is the most predictable assignment — appropriate for an agency nurse unfamiliar with the unit''s protocols.',
  NULL,
  'safe_effective_care',
  'Management of Care',
  NULL,
  'hard',
  false,
  true
),
(
  'A client tells the nurse, ''I do not want my family to know I have been diagnosed with HIV.'' What is the nurse''s best response?',
  'I understand, but your family needs to know for your safety.',
  'Your information is confidential and will not be shared without your consent.',
  'I will need to tell your emergency contact if your condition worsens.',
  'You should tell your family yourself so they can support you.',
  'b',
  'Client confidentiality is a legal and ethical right — the nurse must protect this information unless legally required to disclose.',
  NULL,
  'safe_effective_care',
  'Management of Care',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is preparing to perform a surgical time-out before a procedure. Select ALL components that must be verified during the time-out.',
  'Client identity using two identifiers',
  'Client''s insurance information',
  'Correct surgical site and side',
  'Type of procedure to be performed',
  'a',
  'The surgical time-out (Universal Protocol) requires verification of client identity, correct site/side, procedure type, and positioning.',
  NULL,
  'safe_effective_care',
  'Management of Care',
  NULL,
  'medium',
  true,
  true
),
(
  'A nurse is caring for a client with active pulmonary tuberculosis. Which type of transmission-based precaution is required?',
  'Contact precautions',
  'Droplet precautions',
  'Airborne precautions',
  'Reverse isolation',
  'c',
  'TB is transmitted via airborne droplet nuclei (<5 microns) — airborne precautions with a negative-pressure room and N95 respirator are required.',
  NULL,
  'safe_effective_care',
  'Safety & Infection Prevention',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is preparing to insert a urinary catheter. After opening the sterile field and adding supplies, the nurse''s hand accidentally touches the sterile drape. What should the nurse do?',
  'Continue — the drape is not part of the sterile field',
  'Document the event and proceed carefully',
  'Discard the setup and obtain a new sterile catheter kit',
  'Clean the drape with a sterile alcohol wipe and continue',
  'c',
  'Once a sterile field is contaminated, the entire setup must be discarded and a new sterile kit obtained.',
  NULL,
  'safe_effective_care',
  'Safety & Infection Prevention',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client with Clostridioides difficile (C. diff) diarrhea. Which hand hygiene method is most effective before exiting the room?',
  'Alcohol-based hand rub for 20 seconds',
  'Soap and water handwashing for at least 20 seconds',
  'Chlorhexidine hand wipe followed by hand rub',
  'Either soap or alcohol-based hand rub — both are equally effective',
  'b',
  'C. diff spores are NOT killed by alcohol-based hand rubs — soap and water is required to physically remove the spores.',
  NULL,
  'safe_effective_care',
  'Safety & Infection Prevention',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is caring for four clients. Which client requires contact precautions?',
  'A client with active pulmonary tuberculosis',
  'A client with influenza',
  'A client with a wound infected with methicillin-resistant Staphylococcus aureus (MRSA)',
  'A client with meningococcal meningitis',
  'c',
  'MRSA is transmitted by direct or indirect contact — contact precautions (gown and gloves) are required.',
  NULL,
  'safe_effective_care',
  'Safety & Infection Prevention',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse provides discharge teaching to a client who is 8 weeks pregnant. Which statement requires further teaching?',
  'I will take my prenatal vitamins with a full glass of water daily.',
  'I can have one or two glasses of wine on special occasions.',
  'I should call my provider if I notice decreased fetal movement after 28 weeks.',
  'I will avoid eating raw sushi during my pregnancy.',
  'b',
  'No amount of alcohol is safe in pregnancy — any consumption risks fetal alcohol spectrum disorder.',
  NULL,
  'health_promotion',
  'Health Promotion',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is teaching a 50-year-old client with no family history of colorectal cancer about recommended cancer screenings. Which statement is correct?',
  'Colonoscopy is recommended every 5 years starting at age 45',
  'Colorectal cancer screening should begin at age 50 with annual fecal occult blood testing only',
  'Average-risk individuals should begin colorectal cancer screening at age 45',
  'Screening is only recommended if the client has symptoms',
  'c',
  'The American Cancer Society recommends colorectal cancer screening beginning at age 45 for average-risk individuals.',
  NULL,
  'health_promotion',
  'Health Screening',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is assessing a 15-month-old child during a well-child visit. Which finding should the nurse report to the provider as a developmental concern?',
  'The child uses 5–10 words',
  'The child walks independently',
  'The child does not yet use a spoon',
  'The child does not respond to their name when called',
  'd',
  'Responding to one''s name is a milestone expected by 9–12 months. Failure at 15 months is a red flag for autism spectrum disorder or hearing loss.',
  NULL,
  'health_promotion',
  'Developmental Stages',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is teaching a client about a low-sodium diet. Which meal choice indicates the client understands the teaching?',
  'Canned chicken noodle soup with crackers',
  'Grilled salmon with steamed broccoli and brown rice',
  'A deli turkey sandwich on whole wheat bread',
  'Cottage cheese with canned fruit cocktail',
  'b',
  'Fresh grilled salmon with steamed vegetables and whole grains is naturally low in sodium — an appropriate choice.',
  NULL,
  'health_promotion',
  'Health Promotion',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is teaching a client about reducing cardiovascular risk factors. Select ALL modifiable risk factors the nurse should address.',
  'Hypertension',
  'Family history of heart disease',
  'Cigarette smoking',
  'Age over 65',
  'a',
  'Hypertension, smoking, sedentary lifestyle, and hyperlipidemia are all modifiable through lifestyle changes and/or medications.',
  NULL,
  'health_promotion',
  'Health Promotion',
  NULL,
  'medium',
  true,
  true
),
(
  'A nurse is assessing a client at 36 weeks gestation who reports a sudden onset of painless, bright red vaginal bleeding. Which condition does the nurse suspect?',
  'Abruptio placentae',
  'Placenta previa',
  'Preterm labor',
  'Ruptured ectopic pregnancy',
  'b',
  'Painless bright red vaginal bleeding in the third trimester is the classic presentation of placenta previa — the placenta covers the cervical os.',
  NULL,
  'health_promotion',
  'Ante/Intra/Postpartum',
  NULL,
  'hard',
  false,
  true
),
(
  'A nurse is caring for a client newly diagnosed with type 1 diabetes who states, ''I just don''t believe this is really happening to me.'' Which response is most therapeutic?',
  'Don''t worry — many people live full lives with diabetes.',
  'It sounds like this news is really difficult to process.',
  'You need to start learning about insulin injections today.',
  'Let me get the diabetes educator to speak with you right away.',
  'b',
  'Reflecting the client''s emotional experience demonstrates therapeutic communication and acknowledges feelings without dismissing or redirecting.',
  NULL,
  'psychosocial',
  'Coping & Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A client with schizophrenia tells the nurse, ''The television is sending me secret messages.'' How should the nurse document this finding?',
  'Client reports delusions of reference — TV sends secret messages.',
  'Client is delusional and psychotic.',
  'Client states the television is sending secret messages.',
  'Client appears to be experiencing a hallucination.',
  'c',
  'Objective documentation uses the client''s exact words in quotes — it avoids interpretation and is legally defensible.',
  NULL,
  'psychosocial',
  'Mental Health Concepts',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is triaging calls at a mental health crisis line. A caller states, ''I have a loaded gun in my hand and I''m thinking about ending it.'' What is the nurse''s priority action?',
  'Assess the caller''s support system and encourage them to call a trusted friend',
  'Ask the caller to describe the events that led to this crisis',
  'Direct the caller to emergency services and stay on the line',
  'Schedule a follow-up appointment with a mental health provider',
  'c',
  'This is an imminent safety emergency — the caller has means, plan, and intent. The priority is immediate emergency services while maintaining connection.',
  NULL,
  'psychosocial',
  'Crisis Intervention',
  NULL,
  'hard',
  false,
  true
),
(
  'A client who lost their spouse 3 days ago says, ''I keep expecting to hear his key in the door.'' Which response is most therapeutic?',
  'That is a normal part of grieving — it will get easier with time.',
  'Have you considered speaking with a grief counselor?',
  'It must be very hard not having him here. Tell me more about that.',
  'You need to give yourself permission to heal and move forward.',
  'c',
  'This response acknowledges the client''s pain and invites them to share more — it is empathetic and open-ended.',
  NULL,
  'psychosocial',
  'Therapeutic Communication',
  NULL,
  'medium',
  false,
  true
),
(
  'A client with anorexia nervosa has a BMI of 15.5 and is admitted for medical stabilization. Which nursing priority takes precedence?',
  'Begin therapeutic communication to explore the causes of the eating disorder',
  'Monitor and correct electrolyte imbalances',
  'Implement a structured eating program immediately',
  'Obtain a dietary consult',
  'b',
  'Physiological stability is the priority — severe malnutrition causes life-threatening electrolyte imbalances (especially hypokalemia) that must be corrected first.',
  NULL,
  'psychosocial',
  'Mental Health Concepts',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client who has been prescribed haloperidol. Select ALL findings that indicate the client may be experiencing extrapyramidal side effects (EPS).',
  'Shuffling gait and muscle rigidity',
  'Weight gain of 10 lbs in 2 weeks',
  'Involuntary tongue movements and grimacing',
  'Restlessness and inability to sit still',
  'a',
  'Shuffling gait/rigidity (pseudoparkinsonism), tardive dyskinesia (tongue/facial movements), akathisia (restlessness), and acute dystonia (muscle contractions) are all EPS.',
  NULL,
  'psychosocial',
  'Therapeutic Communication',
  NULL,
  'medium',
  true,
  true
),
(
  'A nurse is caring for a client who is postoperative following abdominal surgery and reports pain of 7/10. The client''s last analgesic was 4 hours ago and is due in 30 minutes. What is the nurse''s best action?',
  'Ask the client to wait 30 minutes until the medication is due',
  'Reposition the client and apply distraction techniques while preparing to administer the medication at the scheduled time',
  'Notify the provider that the current analgesic regimen is ineffective',
  'Contact the provider to request a PRN dose now',
  'b',
  'Non-pharmacological comfort measures (repositioning, distraction) can be used now, while preparing to administer the scheduled analgesic on time — this is the most comprehensive response.',
  NULL,
  'physiological',
  'Basic Care & Comfort',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is caring for a client receiving nasogastric tube feedings. Which action prevents aspiration?',
  'Administer feedings with the head of bed flat',
  'Verify tube placement by auscultating air over the epigastrium',
  'Maintain head of bed elevation at 30–45 degrees during and after feedings',
  'Flush the tube with 10 mL of water before and after each feeding',
  'c',
  'Elevating the head of bed 30–45 degrees uses gravity to keep gastric contents from refluxing into the airway — the primary prevention for aspiration during tube feeding.',
  NULL,
  'physiological',
  'Basic Care & Comfort',
  NULL,
  'easy',
  false,
  true
),
(
  'A nurse is caring for a client with a new tracheostomy. Select ALL interventions the nurse should include in the plan of care.',
  'Keep a spare tracheostomy tube of the same size at the bedside',
  'Suction the airway every hour regardless of clinical assessment',
  'Secure tracheostomy ties with one finger-width of slack',
  'Humidify inspired air or oxygen',
  'a',
  'A spare tube for emergencies, properly secured ties, humidification to prevent secretion crusting, and regular inner cannula changes all maintain airway safety.',
  NULL,
  'physiological',
  'Basic Care & Comfort',
  NULL,
  'medium',
  true,
  true
),
(
  'A nurse is caring for a client with a stage 3 pressure injury on the sacrum. Which intervention is the priority?',
  'Apply a moisture barrier cream to the wound bed',
  'Reposition the client every 2 hours',
  'Irrigate the wound with povidone-iodine solution',
  'Place a donut-shaped foam ring under the sacrum',
  'b',
  'Repositioning every 2 hours relieves pressure — the underlying cause of the injury. Offloading pressure is the priority intervention.',
  NULL,
  'physiological',
  'Basic Care & Comfort',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client receiving IV heparin for pulmonary embolism. The aPTT returns at 180 seconds. What is the priority action?',
  'Continue the infusion and reassess in 6 hours',
  'Increase the infusion rate per protocol',
  'Hold the infusion and notify the provider immediately',
  'Administer protamine sulfate without waiting for orders',
  'c',
  'Therapeutic aPTT is 60–100 seconds. At 180 seconds the client is supratherapeutic with high hemorrhage risk — hold and notify.',
  NULL,
  'physiological',
  'Pharmacological & Parenteral Therapies',
  NULL,
  'hard',
  false,
  true
),
(
  'A nurse is reviewing morning labs for a client on digoxin. Which finding requires holding the medication and contacting the provider?',
  'Serum potassium of 4.2 mEq/L',
  'Serum sodium of 138 mEq/L',
  'Serum digoxin level of 2.4 ng/mL',
  'BUN of 18 mg/dL',
  'c',
  'Therapeutic digoxin is 0.5–2.0 ng/mL. A level of 2.4 ng/mL is toxic — hold and notify.',
  NULL,
  'physiological',
  'Pharmacological & Parenteral Therapies',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client prescribed lithium carbonate for bipolar disorder. Which client statement requires immediate follow-up?',
  'I try to drink about 8 glasses of water a day.',
  'I''ve been having a lot of diarrhea and my hands are shaking.',
  'I take my medication with food to reduce nausea.',
  'I had my lithium level checked last month — it was 0.9.',
  'b',
  'Diarrhea causes sodium and fluid loss, which raises lithium levels. Tremors are a sign of toxicity. This client needs immediate lithium level assessment.',
  NULL,
  'physiological',
  'Pharmacological & Parenteral Therapies',
  NULL,
  'medium',
  false,
  true
),
(
  'A client is receiving vancomycin 1g IV. During the infusion, the nurse notes the client''s face, neck, and upper chest are flushed and red. What is the nurse''s priority action?',
  'Administer diphenhydramine IV and continue the infusion',
  'Stop the infusion and prepare for anaphylaxis treatment',
  'Slow the infusion rate and monitor the client',
  'Discontinue the IV line and notify the provider of a medication error',
  'c',
  'This is Red Man Syndrome — a rate-related reaction to vancomycin, not a true allergy. Slowing the infusion rate typically resolves the reaction.',
  NULL,
  'physiological',
  'Pharmacological & Parenteral Therapies',
  NULL,
  'hard',
  false,
  true
),
(
  'A nurse is preparing to administer a blood transfusion. Select ALL actions the nurse must perform before initiating the infusion.',
  'Verify blood product with two licensed nurses at the bedside',
  'Prime IV tubing with dextrose 5% in water',
  'Obtain baseline vital signs',
  'Ensure IV access with at least an 18-gauge catheter',
  'a',
  'Two-nurse verification, baseline vitals, 18G or larger catheter, and two-identifier client verification are all required before blood transfusion.',
  NULL,
  'physiological',
  'Pharmacological & Parenteral Therapies',
  NULL,
  'medium',
  true,
  true
),
(
  'A nurse is preparing to administer metformin to a client scheduled for a contrast CT scan this afternoon. What is the appropriate action?',
  'Administer the metformin as scheduled',
  'Hold the metformin and notify the provider',
  'Administer half the dose and document',
  'Ask the client if they have had contrast before and proceed accordingly',
  'b',
  'Metformin must be held before and after iodinated contrast due to the risk of contrast-induced nephropathy leading to lactic acidosis.',
  NULL,
  'physiological',
  'Pharmacological & Parenteral Therapies',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client who received an opioid analgesic 30 minutes ago. The client''s respiratory rate is now 8 breaths/min and they are difficult to arouse. What is the priority action?',
  'Administer oxygen via nasal cannula and continue to monitor',
  'Stimulate the client and ask them to take deep breaths',
  'Administer naloxone as ordered and prepare for emergency support',
  'Document the findings and reassess in 15 minutes',
  'c',
  'A respiratory rate of 8 and unresponsiveness indicate opioid-induced respiratory depression — a medical emergency requiring naloxone administration immediately.',
  NULL,
  'physiological',
  'Pharmacological & Parenteral Therapies',
  NULL,
  'hard',
  false,
  true
),
(
  'A nurse is teaching a client newly prescribed warfarin. Which statement by the client indicates a need for further teaching?',
  'I will have my INR checked regularly.',
  'I should avoid drastic changes to how much leafy green vegetables I eat.',
  'I can take ibuprofen for my headaches since it''s not a blood thinner.',
  'I need to report any unusual bruising or bleeding to my provider.',
  'c',
  'NSAIDs like ibuprofen increase bleeding risk when combined with warfarin by inhibiting platelet aggregation — clients should use acetaminophen instead.',
  NULL,
  'physiological',
  'Pharmacological & Parenteral Therapies',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse assesses a client post-thyroidectomy and notes stridor, hoarseness, and tingling around the mouth. Which complication does the nurse suspect?',
  'Thyroid storm',
  'Hypocalcemia due to inadvertent parathyroid removal',
  'Respiratory infection',
  'Recurrent laryngeal nerve damage only',
  'b',
  'Tingling around the mouth and stridor post-thyroidectomy indicate hypocalcemia from accidental parathyroid removal, causing tetany and laryngospasm.',
  NULL,
  'physiological',
  'Reduction of Risk Potential',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client four hours after a lumbar puncture. The client reports a severe headache that worsens when sitting up. What is the priority nursing action?',
  'Administer prescribed acetaminophen and reassess in 1 hour',
  'Encourage the client to increase fluid intake and remain flat',
  'Notify the provider immediately of possible spinal cord injury',
  'Position the client in high-Fowler''s and apply a cold pack',
  'b',
  'This is a classic post-lumbar puncture headache caused by CSF leakage. Lying flat reduces the pressure gradient, and increased fluids help replenish CSF volume.',
  NULL,
  'physiological',
  'Reduction of Risk Potential',
  NULL,
  'hard',
  false,
  true
),
(
  'A nurse is caring for a client with chronic kidney disease (CKD). Which laboratory value is most critical to monitor?',
  'Serum albumin',
  'Serum potassium',
  'Serum calcium',
  'Hemoglobin A1C',
  'b',
  'Hyperkalemia is a life-threatening complication of CKD because impaired kidneys cannot excrete potassium — it can cause fatal dysrhythmias.',
  NULL,
  'physiological',
  'Reduction of Risk Potential',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client who is 12 hours post-op following a right hip replacement. Select ALL findings that require immediate notification of the provider.',
  'Temperature of 37.4°C (99.3°F)',
  'Right calf pain and warmth',
  'Urine output of 20 mL over the past 2 hours',
  'Capillary refill of 2 seconds in the right foot',
  'b',
  'Calf pain/warmth suggests DVT. Urine output of 20 mL/hr is oliguria (normal is ≥30 mL/hr). Uncontrolled pain 30 min after IV analgesic needs reassessment.',
  NULL,
  'physiological',
  'Reduction of Risk Potential',
  NULL,
  'hard',
  true,
  true
),
(
  'A nurse is caring for a client in the ICU with the following ABG results: pH 7.28, PaCO2 52 mmHg, HCO3 24 mEq/L, PaO2 70 mmHg. How should the nurse interpret these results?',
  'Metabolic acidosis, uncompensated',
  'Respiratory acidosis, uncompensated',
  'Respiratory alkalosis, compensated',
  'Metabolic alkalosis, uncompensated',
  'b',
  'pH <7.35 = acidosis. Elevated PaCO2 (>45) = respiratory cause. HCO3 is normal (22–26) = no compensation yet. This is respiratory acidosis, uncompensated.',
  NULL,
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  false,
  true
),
(
  'A nurse is caring for a client with heart failure who has gained 3 lbs overnight and has worsening shortness of breath. Which intervention should the nurse perform first?',
  'Weigh the client again to confirm accuracy',
  'Administer the prescribed PRN furosemide',
  'Elevate the head of bed and apply supplemental oxygen',
  'Restrict the client''s oral fluid intake for the rest of the day',
  'c',
  'Positioning and oxygenation address the immediate symptom of dyspnea first — then pharmacological intervention follows.',
  NULL,
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client with burns over 40% total body surface area who is 6 hours post-injury. The nurse notes urine output of 15 mL/hr. What is the priority action?',
  'Document the finding and reassess in 1 hour',
  'Increase IV fluid administration per the Parkland formula and notify the provider',
  'Restrict fluids to prevent fluid overload',
  'Administer a diuretic to increase urine output',
  'b',
  'Adequate urine output (0.5–1 mL/kg/hr in burn patients) signals adequate resuscitation. 15 mL/hr is inadequate — increase fluids per Parkland formula and notify provider.',
  NULL,
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client with increased intracranial pressure (ICP). Which intervention should the nurse question if ordered?',
  'Elevate the head of bed to 30 degrees',
  'Administer mannitol IV as prescribed',
  'Encourage coughing and deep breathing every 2 hours',
  'Maintain a quiet, low-stimulation environment',
  'c',
  'Coughing increases intrathoracic pressure which impairs cerebral venous drainage and dramatically raises ICP — this intervention is contraindicated.',
  NULL,
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  false,
  true
),
(
  'A nurse is caring for a client in diabetic ketoacidosis (DKA). After IV fluids are initiated, which intervention does the nurse anticipate next?',
  'Administer IV sodium bicarbonate',
  'Begin a regular insulin infusion',
  'Administer IV potassium before starting insulin',
  'Replace fluids with D5W immediately',
  'c',
  'In DKA, insulin drives potassium into cells, causing hypokalemia. IV potassium must be replaced and verified adequate before insulin is started to prevent life-threatening arrhythmias.',
  NULL,
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'A nurse is caring for a client who is 2 days post-op following bowel resection. Which assessment finding indicates the client may be developing anastomotic leak?',
  'Passage of flatus',
  'Serosanguineous wound drainage',
  'Sudden onset of severe abdominal pain with abdominal rigidity',
  'Urine output of 35 mL/hr',
  'c',
  'Sudden severe abdominal pain with rigidity post-bowel surgery is a red flag for anastomotic leak, which can cause peritonitis — a surgical emergency.',
  NULL,
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  false,
  true
),
(
  'A nurse is assessing a client admitted with pneumonia. Which finding is the priority concern?',
  'Temperature 38.6°C (101.5°F)',
  'Productive cough with yellow sputum',
  'Oxygen saturation of 88% on room air',
  'Respiratory rate of 22 breaths per minute',
  'c',
  'SpO2 of 88% indicates significant hypoxemia — immediate supplemental oxygen is required to prevent respiratory failure.',
  NULL,
  'physiological',
  'Physiological Adaptation',
  NULL,
  'medium',
  false,
  true
),
(
  'Which TWO conditions are the nurse''s priority concerns based on this data?',
  'Hypoglycemia',
  'Hypertensive crisis',
  'Sepsis',
  'Medication overdose',
  'a',
  'Glucose of 38 mg/dL is critically low — immediate intervention required. Fever, hypotension, tachycardia, and altered mental status meet SIRS/sepsis criteria. Both are immediate life threats.',
  NULL,
  'safe_effective_care',
  'Management of Care',
  NULL,
  'hard',
  true,
  true
),
(
  'Based on the ECG findings and clinical presentation, which area of the myocardium is most likely affected?',
  'Anterior wall',
  'Lateral wall',
  'Inferior wall',
  'Posterior wall',
  'c',
  'ST elevation in leads II, III, and aVF indicates inferior wall MI, typically caused by right coronary artery occlusion.',
  NULL,
  'physiological',
  'Physiological Adaptation',
  NULL,
  'hard',
  true,
  true
),
(
  'Which structure allows blood to bypass the fetal liver, shunting it directly from the umbilical vein to the inferior vena cava?',
  'Ductus arteriosus',
  'Foramen ovale',
  'Ductus venosus',
  'Umbilical artery',
  'c',
  'Ductus venosus = umbilical vein → IVC (bypasses liver). Ductus arteriosus = pulmonary artery → aorta (bypasses lungs).',
  'm1',
  NULL,
  NULL,
  'Newborn Circulation',
  'easy',
  false,
  true
),
(
  'A parent asks why their newborn is receiving vitamin K immediately after birth. What is the nurse''s best response?',
  'It prevents eye infections during delivery.',
  'Newborns lack clotting factors — Vitamin K prevents hemorrhagic disease of the newborn.',
  'It''s required by law — no specific reason for your baby.',
  'It prevents jaundice by helping the liver process bilirubin.',
  'b',
  'Vit K prevents HDN (hemorrhagic disease of newborn). Erythromycin eye ointment = eye infections. Vit K ≠ bilirubin.',
  'm1',
  NULL,
  NULL,
  'Newborn Medications',
  'easy',
  false,
  true
),
(
  'A breastfeeding mother asks how she will know if her newborn is getting enough on day 2 postpartum. Which response is most accurate?',
  'By day 2, your baby should have 6–8 wet diapers per day.',
  'By day 2, at least 2 wet diapers — wet diapers are the best signs of adequate intake.',
  'Weight gain is the only reliable way to know.',
  'Your baby should sleep at least 4 hours between feeds.',
  'b',
  'Day 1→1, Day 2→2, Day 3→3, Day 4+→6–8 wet diapers. Longer sleep stretches = concern, not reassurance.',
  'm1',
  NULL,
  NULL,
  'Feeding & Wet Diapers',
  'easy',
  false,
  true
),
(
  'Which physiological consequence of cold stress in newborns is most important to understand?',
  'Cold stress decreases oxygen consumption',
  'Cold stress increases surfactant production',
  'Cold stress increases blood glucose',
  'Cold stress increases oxygen consumption, causing hypoglycemia and respiratory distress',
  'd',
  'Cold stress → nonshivering thermogenesis → ↑ O₂ consumption, ↓ glucose, ↓ surfactant. Cold babies = hypoglycemic babies.',
  'm1',
  NULL,
  NULL,
  'Cold Stress',
  'easy',
  false,
  true
),
(
  'A nurse assesses a 1-hour-old newborn with grunting on expiration, nasal flaring, and intercostal retractions. How should these findings be interpreted?',
  'Normal transitional breathing in the first hour of life',
  'Signs of respiratory distress requiring immediate intervention',
  'Expected in a newborn who has been crying vigorously',
  'Signs the newborn is hungry',
  'b',
  'Grunting, flaring, retractions = classic respiratory distress signs. Require immediate action.',
  'm1',
  NULL,
  NULL,
  'Respiratory Distress',
  'easy',
  false,
  true
),
(
  'A new mother is tearful that her baby has lost weight. How should the nurse respond?',
  'Weight loss is abnormal — I''ll notify the provider.',
  'Weight loss up to 10% is normal. Birth weight is regained by 10–14 days. Use wet diapers as your daily guide.',
  'Any weight loss means we need to start formula right away.',
  'Newborns should not lose any weight in the first 24 hours.',
  'b',
  'Up to 10% weight loss in first few days = physiologically normal. Regained by day 10–14.',
  'm1',
  NULL,
  NULL,
  'Weight Loss',
  'easy',
  false,
  true
),
(
  'A nurse notes yellowing of a newborn''s skin at 36 hours. The newborn is feeding well. How should the nurse classify this?',
  'Pathological — jaundice should not appear until after 48 hours',
  'Physiological — expected; jaundice appearing after 24 hours is physiologic',
  'Concerning — suggests ABO incompatibility',
  'Normal — jaundice in the first 24 hours is always expected',
  'b',
  'KEY PEARL: Jaundice AFTER 24 hrs = physiologic. Jaundice WITHIN first 24 hrs = ALWAYS pathological.',
  'm1',
  NULL,
  NULL,
  'Jaundice',
  'easy',
  false,
  true
),
(
  'APGAR at 1 min: HR 90, weak cry, some flexion, grimace only, acrocyanosis. What is the APGAR score and priority action?',
  'Score 5 — stimulate and supplemental O₂, reassess at 5 min',
  'Score 7 — routine newborn care',
  'Score 3 — immediate resuscitation',
  'Score 8 — reassure parents',
  'a',
  'HR 90(1)+weak cry(1)+some flexion(1)+grimace(1)+acrocyanosis(1) = APGAR 5. Score 4–6 → stimulate + O₂.',
  'm1',
  NULL,
  NULL,
  'APGAR Scores',
  'medium',
  false,
  true
),
(
  'A nurse is assessing a 12-hour-old newborn. Select ALL findings that require IMMEDIATE provider notification.',
  'Acrocyanosis of the hands and feet',
  'Persistent nasal grunting between feedings',
  'Central cyanosis of the lips and tongue',
  'Vernix caseosa on skin folds',
  'b',
  'Persistent grunting, central cyanosis, and apnea = report immediately. Acrocyanosis, vernix, milia = normal.',
  'm1',
  NULL,
  NULL,
  'Expected vs. Unexpected Findings',
  'medium',
  true,
  true
),
(
  '2-hour-old: RR 74, central cyanosis, intercostal retractions, grunting, SpO₂ 86%. Priority action?',
  'Document and reassess in 30 minutes',
  'Ensure airway is open, call for immediate assistance, prepare O₂',
  'Warm under radiant warmer to rule out cold stress',
  'Feed to provide glucose and stimulate respiratory effort',
  'b',
  'SpO₂ 86% + central cyanosis + retractions = respiratory emergency. ABCs first — airway and call for help.',
  'm1',
  NULL,
  NULL,
  'Respiratory Distress',
  'medium',
  false,
  true
),
(
  '4-hour-old: jittery, weak cry, difficult to arouse, blood glucose 36 mg/dL. First action?',
  'Draw full metabolic panel and wait for results',
  'Feed the newborn (breast or formula) per hypoglycemia protocol',
  'Administer IV dextrose immediately',
  'Place under radiant warmer, recheck in 2 hours',
  'b',
  'Feed first if tolerated — oral feeding is first-line for neonatal hypoglycemia. IV glucose reserved for failure to feed or respond.',
  'm1',
  NULL,
  NULL,
  'Hypoglycemia',
  'medium',
  false,
  true
),
(
  'Select ALL interventions that prevent heat loss and support thermoregulation after delivery.',
  'Dry newborn with warm blankets',
  'Place on cold infant scale immediately',
  'Maintain warm, draft-free delivery room',
  'Encourage skin-to-skin contact',
  'a',
  'Drying, warm environment, skin-to-skin, hat, swaddling = prevent heat loss. Cold scale = causes heat loss (conductive).',
  'm1',
  NULL,
  NULL,
  'Thermoregulation',
  'medium',
  true,
  true
),
(
  'Which parent statement during discharge teaching indicates a need for further teaching?',
  'I will always place my baby on her back to sleep.',
  'We have a firm, flat crib mattress with a fitted sheet.',
  'I''ll put a soft blanket in the crib so she stays warm.',
  'She can sleep in our room in her own bassinet.',
  'c',
  'Soft blankets in sleep space = suffocation hazard. Safe sleep: back, firm surface, no soft objects, room sharing (not bed sharing).',
  'm1',
  NULL,
  NULL,
  'Safe Sleep',
  'medium',
  false,
  true
),
(
  'Which instruction about umbilical cord care should the nurse include in discharge teaching?',
  'Apply antibiotic ointment daily',
  'Fold diaper below stump, keep clean and dry, expect separation in 7–14 days',
  'Submerge in tub bath daily to soften cord',
  'Cord should fall off in 3–4 days; call if it lasts longer',
  'b',
  'Keep dry and clean, fold diaper below, off in 7–14 days. No tub baths until cord falls off. No antibiotic ointment routinely.',
  'm1',
  NULL,
  NULL,
  'Umbilical Cord Care',
  'medium',
  false,
  true
),
(
  'Home health nurse visits a 5-day-old breastfed newborn. Mother reports 4 wet diapers yesterday. How should the nurse interpret this?',
  'Normal — 4 wet diapers is appropriate for a 5-day-old',
  'Concerning — day 4+ should have 6–8 wet diapers per day; 4 suggests inadequate intake',
  'Normal — wet diaper count peaks day 3 and decreases after',
  'Concerning — a 5-day-old should have at least 10 wet diapers',
  'b',
  'Day 4+ = 6–8 wet diapers expected. At day 5, only 4 = inadequate — assess latch, frequency, weight.',
  'm1',
  NULL,
  NULL,
  'Feeding & Wet Diapers',
  'medium',
  false,
  true
),
(
  'Select ALL newborn findings in the nursery that require IMMEDIATE provider notification.',
  'Mongolian spots on sacral area',
  'Central cyanosis of lips and tongue',
  'Apnea episode during assessment',
  'Acrocyanosis of hands and feet',
  'b',
  'Central cyanosis, apnea, seizures, temp instability, lethargy/poor feeding = report immediately. Mongolian spots, acrocyanosis, lanugo = normal.',
  'm1',
  NULL,
  NULL,
  'Report Immediately',
  'medium',
  true,
  true
),
(
  'A nursing student sees blue discoloration of a newborn''s hands and feet and asks if it should be reported. Best teaching response?',
  'Yes — any blue discoloration is a cardiac emergency.',
  'No — blue hands/feet (acrocyanosis) is normal. Blue lips/tongue is the emergency we watch for.',
  'Yes — this is central cyanosis, prepare O₂ immediately.',
  'No — newborns are blue all over for the first 24 hours.',
  'b',
  'MOST COMMON NCLEX TRAP: Acrocyanosis (blue extremities) = NORMAL. Central cyanosis (lips/tongue/trunk) = EMERGENCY.',
  'm1',
  NULL,
  NULL,
  'NCLEX Traps',
  'hard',
  false,
  true
),
(
  'Bow-Tie: 30-min-old newborn, unwrapped, Temp 35.9°C, HR 176, RR 66, glucose 36 mg/dL, jittery.',
  'Left: Dry and swaddle in warm blankets',
  'Left: Skin-to-skin contact',
  'Left: Tepid bath to stimulate temp regulation',
  'Left: Restrict oral feeds',
  'a',
  'Cold stress → hypoglycemia. Dry/swaddle + skin-to-skin = warm. Monitor temp and glucose trends.',
  'm1',
  NULL,
  NULL,
  'Cold Stress',
  'hard',
  true,
  true
),
(
  'Bow-Tie: 38-wk LGA newborn, 1hr old, GDM mother, jittery, weak cry, glucose 34 mg/dL.',
  'Left: Feed per hypoglycemia protocol',
  'Left: Restrict feeds, await IV glucose',
  'Left: Recheck glucose 30 min after feeding',
  'Center: Neonatal hypoglycemia',
  'a',
  'LGA + DM mother = fetal hyperinsulinism. Feed first, recheck glucose. IV glucose only if oral fails.',
  'm1',
  NULL,
  NULL,
  'Hypoglycemia',
  'hard',
  true,
  true
),
(
  '[Case Study A] 2-hr-old: RR 78, grunting, flaring, retractions, SpO₂ 86%, central cyanosis. Which finding is most immediately life-threatening?',
  'HR 182 bpm',
  'Central cyanosis with SpO₂ 86%',
  'RR 78',
  'Temp 37.0°C',
  'b',
  'Central cyanosis + SpO₂ 86% = severe hypoxemia. Most immediately life-threatening. ABCs first.',
  'm1',
  NULL,
  NULL,
  'Respiratory Distress',
  'hard',
  true,
  true
),
(
  '[Case Study B] Same patient. Select ALL signs of neonatal respiratory distress.',
  'Nasal flaring',
  'Grunting on expiration',
  'Pale skin',
  'Intercostal retractions',
  'a',
  'Flaring, grunting, retractions, central cyanosis = RDS signs. Normal temp and pale skin are not RDS criteria.',
  'm1',
  NULL,
  NULL,
  'Respiratory Distress',
  'hard',
  true,
  true
),
(
  '[Case Study C] ABC framework. What is the nurse''s FIRST priority action?',
  'Call parents',
  'Document all findings',
  'Ensure airway is patent and call for immediate respiratory support',
  'Obtain blood glucose to rule out hypoglycemia',
  'c',
  'ABCs — Airway first. Ensure patent airway and call for help. Documentation and glucose come after.',
  'm1',
  NULL,
  NULL,
  'Respiratory Distress',
  'hard',
  true,
  true
),
(
  '[Case Study A] 18-hr-old, mother O+, baby A+, poor feeding, 1 wet diaper. How should the nurse classify the jaundice?',
  'Physiological — after 12 hours is normal',
  'Pathological — jaundice within 24 hours is always concerning',
  'Normal — all newborns develop visible jaundice in first 24 hours',
  'Mild — monitor at home',
  'b',
  'Jaundice within FIRST 24 hours = ALWAYS pathological. This is the critical NCLEX distinction.',
  'm1',
  NULL,
  NULL,
  'Jaundice',
  'hard',
  true,
  true
),
(
  '[Case Study B] Same patient. Which finding is most consistent with the likely cause?',
  'Blood type incompatibility — O+ mother, A+ newborn',
  'Lanugo on back',
  'Mongolian spots',
  'Acrocyanosis',
  'a',
  'ABO incompatibility (O+ mom + A+ or B+ baby) → maternal antibodies cross placenta → hemolysis → pathological jaundice.',
  'm1',
  NULL,
  NULL,
  'Jaundice',
  'hard',
  true,
  true
),
(
  '[Case Study C] Same patient. Select ALL appropriate nursing actions.',
  'Notify provider immediately',
  'Monitor bilirubin per order',
  'Reassure parents this is normal physiologic jaundice',
  'Encourage frequent feeding',
  'a',
  'Notify, monitor bili, feed frequently, assess for hemolysis, prep for phototherapy. Do NOT reassure as normal — it is pathological.',
  'm1',
  NULL,
  NULL,
  'Jaundice',
  'hard',
  true,
  true
),
(
  'Select ALL newborn nursery findings requiring IMMEDIATE intervention — above documentation or routine care.',
  'Central cyanosis of the lips in a 3-hr-old',
  'Grunting and flaring with RR 78 in a 1-hr-old',
  'Mongolian spots on sacral area of a 2-day-old',
  'Glucose 36 mg/dL with jitteriness in an LGA infant',
  'a',
  'Central cyanosis, RDS, hypoglycemia, hypothermia+lethargy, apnea = immediate. Mongolian spots, acrocyanosis, vernix = normal.',
  'm1',
  NULL,
  NULL,
  'Priority Assessments',
  'hard',
  true,
  true
),
(
  'Which scenario places a fetus at risk for hemolytic disease of the newborn?',
  'Rh+ mother / Rh– baby',
  'Rh– mother / Rh+ baby',
  'Rh+ mother / Rh+ baby',
  'Rh– mother / Rh– baby',
  'b',
  'Rh– mom + Rh+ baby = risk for hemolytic disease. Mom''s antibodies attack baby''s RBCs.',
  'm2',
  NULL,
  NULL,
  'RH Incompatibility',
  'easy',
  false,
  true
),
(
  'An Rh-negative patient delivers an Rh-positive infant. RhoGAM must be administered within which postpartum timeframe?',
  '24 hours',
  '48 hours',
  '72 hours',
  '1 week',
  'c',
  'RhoGAM must be given within 72 hours postpartum to prevent sensitization.',
  'm2',
  NULL,
  NULL,
  'RH Incompatibility',
  'easy',
  false,
  true
),
(
  'Which combination of findings establishes a diagnosis of preeclampsia?',
  'BP ≥140/90 after 20 weeks with no proteinuria',
  'BP ≥140/90 after 20 weeks + proteinuria ≥300 mg/24 hr',
  'Seizures in a patient with elevated BP',
  'BP ≥120/80 with severe headache after 20 weeks',
  'b',
  'Preeclampsia = HTN ≥140/90 after 20 wks + proteinuria ≥300 mg/24hr. No protein = Gestational HTN only.',
  'm2',
  NULL,
  NULL,
  'Hypertensive Disorders',
  'easy',
  false,
  true
),
(
  'Low platelets, elevated liver enzymes, and signs of hemolysis are consistent with which complication?',
  'Gestational hypertension',
  'Preeclampsia',
  'HELLP syndrome',
  'Eclampsia',
  'c',
  'HELLP = Hemolysis, Elevated Liver enzymes, Low Platelets. May present with RUQ pain, N/V.',
  'm2',
  NULL,
  NULL,
  'Hypertensive Disorders',
  'easy',
  false,
  true
),
(
  'Early decelerations — FHR dips symmetrically and returns to baseline with each contraction. Best nursing interpretation?',
  'Umbilical cord compression — reposition the patient',
  'Placental insufficiency — notify provider immediately',
  'Head compression — usually benign, no intervention needed',
  'Fetal distress — prepare for emergency delivery',
  'c',
  'Early decels = head compression = benign. Return to baseline mirrors contraction. No intervention needed.',
  'm2',
  NULL,
  NULL,
  'Fetal Heart Rate Patterns',
  'easy',
  false,
  true
),
(
  'Recurrent decelerations begin AFTER the peak of each contraction and return to baseline slowly. Priority action?',
  'Document and continue monitoring',
  'Reposition to left lateral, O₂, IV fluids, notify provider, stop Pitocin',
  'Increase Pitocin to strengthen contractions',
  'Administer pain medication',
  'b',
  'Late decels = placental insufficiency = OMINOUS. Reposition left, O₂, IVF, notify provider, stop Pitocin.',
  'm2',
  NULL,
  NULL,
  'Fetal Heart Rate Patterns',
  'easy',
  false,
  true
),
(
  'Which fundal height finding correctly corresponds to gestational age?',
  'Fundal height at the umbilicus = 12 weeks',
  'Fundal height at the umbilicus = 20 weeks',
  'Fundal height at the xiphoid process = 28 weeks',
  'Fundal height just above symphysis = 20 weeks',
  'b',
  '20 wks = umbilicus. 12 wks = just above symphysis. 36 wks = xiphoid process.',
  'm2',
  NULL,
  NULL,
  'Prenatal Pearls',
  'easy',
  false,
  true
),
(
  'Select ALL vaccines considered safe and recommended during pregnancy.',
  'Tdap (27–36 weeks)',
  'MMR',
  'Influenza (injectable)',
  'Varicella (chickenpox)',
  'a',
  'Safe: Tdap, injectable flu, COVID, RSV. AVOID live vaccines: MMR, Varicella, FluMist, Shingles.',
  'm2',
  NULL,
  NULL,
  'Vaccines in Pregnancy',
  'easy',
  true,
  true
),
(
  'Teaching a patient at 30 weeks about kick counts. Which instruction is most accurate?',
  'Count kicks starting at 20 weeks',
  'Feel for 10 movements in 2 hours — call provider if fewer',
  'Count only during morning hours for accuracy',
  '5 movements per hour is the expected minimum',
  'b',
  'Kick counts begin at 28 weeks. Goal = 10 movements in 2 hours. Call provider if fewer than 10.',
  'm2',
  NULL,
  NULL,
  'Prenatal Pearls',
  'easy',
  false,
  true
),
(
  'Which lab finding is considered NORMAL during pregnancy?',
  'Proteinuria ≥300 mg/24 hr',
  'Platelet count of 80,000',
  'Mild dilutional anemia (decreased Hgb/Hct)',
  'Elevated creatinine',
  'c',
  'Dilutional anemia = normal (plasma volume ↑ more than RBC). Proteinuria ≥300 mg = preeclampsia. Low platelets + elevated creatinine = concerning.',
  'm2',
  NULL,
  NULL,
  'Labs in Pregnancy',
  'easy',
  false,
  true
),
(
  'Patient A: sudden severe abdominal pain, rigid uterus, dark red bleeding. Patient B: painless bright red bleeding, no contractions. Which best distinguishes them?',
  'Patient A has placenta previa; Patient B has abruption',
  'Patient A has placental abruption; Patient B has placenta previa',
  'Both have the same condition — placenta previa',
  'Both need vaginal exams to distinguish',
  'b',
  'Abruption = PAINFUL, dark red, rigid uterus. Previa = PAINLESS, bright red. NO vaginal exam with previa.',
  'm2',
  NULL,
  NULL,
  'Obstetric Emergencies',
  'medium',
  false,
  true
),
(
  '32-week patient with painless bright red vaginal bleeding, suspected placenta previa. Priority nursing action?',
  'Perform a vaginal exam to assess cervical dilation',
  'Apply fundal pressure',
  'Do NOT perform vaginal exam — place on bed rest, notify provider, monitor mom and fetus',
  'Encourage ambulation to stimulate contractions',
  'c',
  'Placenta previa: NO vaginal exam (can cause hemorrhage). Place on bed rest, notify provider, monitor.',
  'm2',
  NULL,
  NULL,
  'Obstetric Emergencies',
  'medium',
  false,
  true
),
(
  'Umbilical cord is visible at the vaginal introitus after membrane rupture. Priority nursing action?',
  'Push the cord back into the vagina',
  'Knee-chest position, do NOT push cord in, lift presenting part, call for emergency help',
  'Place on her back and monitor fetal HR',
  'Prepare for immediate vaginal delivery',
  'b',
  'Cord prolapse: Knee-chest position, NEVER push cord in, manually lift presenting part off cord, EMERGENCY call.',
  'm2',
  NULL,
  NULL,
  'Obstetric Emergencies',
  'medium',
  false,
  true
),
(
  'Variable decelerations — abrupt FHR drops varying in timing and depth. Priority action?',
  'Document and continue routine monitoring',
  'Increase Pitocin rate',
  'Reposition the patient, administer O₂, increase IV fluids',
  'Notify provider to prepare for immediate C-section',
  'c',
  'Variable decels = cord compression. First: reposition (left lateral or knee-chest), O₂, IVF. Notify if persist.',
  'm2',
  NULL,
  NULL,
  'Fetal Heart Rate Patterns',
  'medium',
  false,
  true
),
(
  'Patient on IV magnesium sulfate: respirations 10/min, absent DTRs, decreased urine output. Priority action?',
  'Increase the Mag drip rate to maintain therapeutic levels',
  'Stop the infusion and administer calcium gluconate IV',
  'Reposition to left lateral and increase fluids',
  'Document and reassess in 30 minutes',
  'b',
  'Mag toxicity signs (resp <12, absent DTRs, ↓ UO) → STOP infusion + give calcium gluconate (antidote) immediately.',
  'm2',
  NULL,
  NULL,
  'Hypertensive Disorders',
  'medium',
  false,
  true
),
(
  'Chart records G4 T2 P1 A1 L2. How should the nurse correctly interpret this GTPAL?',
  '4 pregnancies, 2 term births, 1 preterm, 1 abortion, 2 living children',
  '4 deliveries, 2 premature, 1 term, 1 abortion, 2 living',
  '4 pregnancies, 2 term, 1 stillbirth, 1 abortion, 2 living',
  '4 pregnancies, 2 term, 1 preterm, 1 stillbirth, 2 living',
  'a',
  'GTPAL: G=Gravida(total pregnancies), T=Term births, P=Preterm births, A=Abortions/losses, L=Living children.',
  'm2',
  NULL,
  NULL,
  'Prenatal Pearls',
  'medium',
  false,
  true
),
(
  'An Rh-negative patient at 14 weeks has a positive indirect Coombs test. Most important nursing implication?',
  'Administer RhoGAM immediately',
  'The patient is already sensitized — RhoGAM will NOT prevent further hemolysis',
  'Schedule RhoGAM at 28 weeks as planned',
  'Prepare for emergency delivery',
  'b',
  'Positive indirect Coombs = already sensitized. RhoGAM prevents sensitization — it CANNOT treat existing sensitization.',
  'm2',
  NULL,
  NULL,
  'RH Incompatibility',
  'medium',
  false,
  true
),
(
  'Select ALL prenatal findings that require IMMEDIATE provider notification.',
  'Mild ankle edema at the end of a long day',
  'Sudden severe headache at 32 weeks',
  'Painless bright red vaginal bleeding at 30 weeks',
  'Nausea in the first trimester',
  'b',
  'Severe headache, bright red bleeding, visual changes + RUQ pain, decreased fetal movement = report immediately. Ankle edema and 1st trimester nausea = normal.',
  'm2',
  NULL,
  NULL,
  'Report Immediately',
  'medium',
  true,
  true
),
(
  'Which urinalysis finding requires IMMEDIATE provider notification in a pregnant patient?',
  'Trace protein on dipstick',
  'Glycosuria in the absence of other symptoms',
  'Proteinuria 2+ on dipstick at 28 weeks',
  '↑ urinary frequency without dysuria',
  'c',
  'Proteinuria 2+ = significant protein loss. After 20 wks, combined with HTN = preeclampsia. Always report. Trace protein may be ok, but more than trace = NOT normal.',
  'm2',
  NULL,
  NULL,
  'Labs in Pregnancy',
  'medium',
  false,
  true
),
(
  'Nurse receives four messages simultaneously. Which patient should be assessed FIRST?',
  '28-week patient reporting decreased fetal movement for 4 hours',
  '36-week patient with mild ankle edema',
  '32-week patient experiencing first-trimester-type nausea',
  '38-week patient with Braxton Hicks every 20 minutes',
  'a',
  'Decreased fetal movement at 28 weeks = report immediately. Reassure patient movement is the baby communicating.',
  'm2',
  NULL,
  NULL,
  'Priority Nursing',
  'medium',
  false,
  true
),
(
  'Bow-Tie: 34-wk patient with BP 168/112, severe headache, 3+ proteinuria, RUQ pain, hyperreflexia.',
  'Left: Administer IV magnesium sulfate per order',
  'Left: Keep calcium gluconate at bedside',
  'Left: Increase Pitocin',
  'Center: Severe preeclampsia',
  'a',
  'Severe preeclampsia: Mag for seizure prevention, calcium gluconate antidote at bedside. Monitor resp, DTRs, and UO for toxicity.',
  'm2',
  NULL,
  NULL,
  'Hypertensive Disorders',
  'hard',
  true,
  true
),
(
  'Bow-Tie: Active labor patient — cord felt at introitus after spontaneous ROM, FHR 90 bpm.',
  'Left: Knee-chest position immediately',
  'Left: Push cord back into vagina',
  'Left: Manually lift presenting part off cord',
  'Center: Umbilical cord prolapse',
  'a',
  'Cord prolapse = emergency. Knee-chest, lift presenting part, never push cord in. Monitor FHR and cord perfusion.',
  'm2',
  NULL,
  NULL,
  'Obstetric Emergencies',
  'hard',
  true,
  true
),
(
  '[Case Study A] 32-wk patient: BP 158/106, HA, visual changes, 2+ proteinuria, hyperreflexia. Which assessment finding requires PRIORITY action before starting Mag?',
  'Current blood pressure reading',
  'Baseline respiratory rate, DTRs, and urine output',
  'Fetal heart rate tracing',
  'Severity of headache on 1–10 scale',
  'b',
  'Before starting Mag, establish baseline: resp rate (must be ≥12), DTRs, and urine output to monitor for toxicity.',
  'm2',
  NULL,
  NULL,
  'Hypertensive Disorders',
  'hard',
  true,
  true
),
(
  '[Case Study B] 1 hour into Mag infusion. Select ALL findings that indicate MAGNESIUM TOXICITY.',
  'Respirations 8 per minute',
  'BP 150/100',
  'Absent deep tendon reflexes',
  'Urine output 15 mL/hr',
  'a',
  'Mag toxicity: resp <12, absent DTRs, UO <30 mL/hr, and toxic Mag level (>9 mEq/L) → STOP infusion + calcium gluconate.',
  'm2',
  NULL,
  NULL,
  'Hypertensive Disorders',
  'hard',
  true,
  true
),
(
  '[Case Study C] Patient has generalized tonic-clonic seizure (eclampsia). Priority nursing action DURING the seizure?',
  'Restrain the patient and insert oral airway',
  'Protect from injury, maintain airway, turn to side, call for help, note seizure duration',
  'Document the seizure and notify physician after it ends',
  'Administer calcium gluconate IV push immediately',
  'b',
  'During seizure: protect from injury, side-lying (airway/aspiration), call for help, time it. Calcium gluconate = Mag antidote, not seizure treatment.',
  'm2',
  NULL,
  NULL,
  'Hypertensive Disorders',
  'hard',
  true,
  true
),
(
  '[Case Study A] 4 antepartum patients. Using ''MOM FIRST'' — which patient do you see FIRST?',
  '38-wk patient with Braxton Hicks every 15 min, no cervical change',
  '32-wk patient with BP 172/114, visual changes, and RUQ pain',
  '34-wk patient with painless bright red vaginal bleeding (placenta previa)',
  '28-wk patient with regular contractions q5min, cervical change to 3 cm',
  'b',
  'BP 172/114 + visual changes + RUQ pain = severe preeclampsia with imminent eclampsia risk = MOST urgent life threat.',
  'm2',
  NULL,
  NULL,
  'Priority Nursing',
  'hard',
  true,
  true
),
(
  '[Case Study B] For the placenta previa patient — which action is CONTRAINDICATED?',
  'Placing patient on bed rest',
  'Monitoring fetal heart tones continuously',
  'Performing a vaginal exam to assess dilation',
  'Establishing IV access',
  'c',
  'NEVER do vaginal exam with placenta previa — can precipitate massive hemorrhage. Bed rest, FHT monitoring, and IV access are all appropriate.',
  'm2',
  NULL,
  NULL,
  'Obstetric Emergencies',
  'hard',
  true,
  true
),
(
  '[Case Study C] The 28-week preterm labor patient — which medication would the nurse MOST likely anticipate?',
  'Oxytocin (Pitocin) to strengthen contractions',
  'Betamethasone (corticosteroid) to accelerate fetal lung maturity',
  'Calcium gluconate to treat preterm labor',
  'Magnesium sulfate as a tocolytic AND for fetal neuroprotection',
  'd',
  'Mag sulfate = tocolytic + fetal neuroprotection before 32 weeks. Betamethasone also likely. Pitocin would worsen labor.',
  'm2',
  NULL,
  NULL,
  'Obstetric Emergencies',
  'hard',
  true,
  true
),
(
  'Select ALL antepartum findings that require IMMEDIATE provider notification — above all other tasks.',
  'Vaginal bleeding at 28 weeks',
  'Mild ankle edema at 36 weeks',
  'Severe headache with visual changes at 30 weeks',
  'Regular contractions at 33 weeks',
  'a',
  'Bleeding, severe HA+visual changes, preterm contractions, decreased FM, fluid leaking, dizziness/syncope = report immediately. Ankle edema and 1st trimester nausea = normal.',
  'm2',
  NULL,
  NULL,
  'Report Immediately',
  'hard',
  true,
  true
);
